### ISSUE TITLE
Possibly undefined macro  AC_LINK_IFELSE

### ISSUE THREAD

**Issue by arnold-jr** [lanl/MPI-Bash#4] opened 2017-02-06 17:26 UTC
I cloned the repo and tried to install on top of existing bash 4.1.2 running on Centos6. However, I'm failing to generate the configure (using autoconf 2.69) file with the following message:
```
$ autoreconf -fvi
autoreconf -fvi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /usr/local/bin/autoconf --force
configure.ac:77: error: possibly undefined macro: AC_LINK_IFELSE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:78: error: possibly undefined macro: AC_LANG_SOURCE
autoreconf: /usr/local/bin/autoconf failed with exit status: 1
```

Thanks!

**Comment by spakin** [comment] 2017-02-09 16:25
Strange.  `AC_LINK_IFELSE` and `AC_LANG_SOURCE` ought to be defined in Autoconf 2.69.  That's the version of Autoconf I have, although I'm running under Ubuntu 16.10.

I see you're running `autoconf` from `/usr/local/bin`.  Is it possible that this newer `autoconf` is pulling in its support files from an older `/usr/share/autoconf` instead of `/usr/local/share/autoconf`?  I can't think of why else you'd be missing those macros.

— Scott

**Comment by spakin** [comment] 2017-05-11 16:25
As I can't reproduce this problem (and it's been 3 months since the issue was opened), I'm going to close this issue.  Please re-open if you have any further information to add.

— Scott

**Closed by spakin** 2017-05-11 16:25 UTC
